#!/bin/sh

# PROVIDE: MasterSwiscoin
# REQUIRE: LOGIN
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# MasterSwiscoin_enable (bool): Set to NO by default. Set this variable to YES if you want to enable MasterSwiscoin service.
# MasterSwiscoin_config (path): Set to /usr/local/etc/MasterSwiscoin.conf by default.
# MasterSwiscoin_user:  The user account MasterSwiscoin daemon runs as. It uses 'root' user by default.
# MasterSwiscoin_group: The group account MasterSwiscoin daemon runs as. It uses 'wheel' group by default.
# MasterSwiscoin_datadir (str): Default to "/var/db/MasterSwiscoin". Base data directory.

. /etc/rc.subr

name=MasterSwiscoin
rcvar=MasterSwiscoin_enable

: ${MasterSwiscoin_enable:=NO}
: ${MasterSwiscoin_config=/usr/local/etc/MasterSwiscoin.conf}
: ${MasterSwiscoin_datadir=/var/db/MasterSwiscoin}
: ${MasterSwiscoin_user="root"}
: ${MasterSwiscoin_group="wheel"}

required_files=${MasterSwiscoin_config}
command=/usr/local/bin/MasterSwiscoind
MasterSwiscoin_chdir=${MasterSwiscoin_datadir}
pidfile="${MasterSwiscoin_datadir}/MasterSwiscoind.pid"
stop_cmd=MasterSwiscoin_stop
command_args="-conf=${MasterSwiscoin_config} -datadir=${MasterSwiscoin_datadir} -daemon -pid=${pidfile}"
start_precmd="${name}_prestart"

MasterSwiscoin_create_datadir()
{
	echo "Creating data directory"
	eval mkdir -p ${MasterSwiscoin_datadir}
	[ $? -eq 0 ] && chown -R ${MasterSwiscoin_user}:${MasterSwiscoin_group} ${MasterSwiscoin_datadir}
}

MasterSwiscoin_prestart()
{
	if [ ! -d "${MasterSwiscoin_datadir}/." ]; then
		MasterSwiscoin_create_datadir || return 1
	fi
}

MasterSwiscoin_requirepidfile()
{
	if [ ! "0`check_pidfile ${pidfile} ${command}`" -gt 1 ]; then
		echo "${name} not running? (check $pidfile)."
		exit 1
	fi
}

MasterSwiscoin_stop()
{
    MasterSwiscoin_requirepidfile

	echo "Stopping ${name}."
	eval ${command} -conf=${MasterSwiscoin_config} -datadir=${MasterSwiscoin_datadir} stop
	wait_for_pids ${rc_pid}
}

load_rc_config $name
run_rc_command "$1"
